# CEO-letter specificity, sentiment, and abnormal returns

This extends the validated CAR analysis with overall FinBERT sentiment, ESG-specific sentiment, interactions, and `[0,+5]`/`[0,+20]` CAR windows. It uses frozen classifier and event-study outputs and makes no causal claim.

In [1]:
from pathlib import Path
import sys, pandas as pd
from IPython.display import display, Markdown
ROOT=Path.cwd(); sys.path.insert(0,str(ROOT))
from specificity_car_test.analysis_sentiment import main

## Merge and definitions

Primary specificity is the existing Corporate tier≥1 mean. Overall sentiment is positive share minus negative share across all sentences. ESG sentiment applies the same formula to ESG-flagged sentences. Tier 0 is a false positive and is not redefined as generic.

In [2]:
audit, descriptive, correlations, results = main()
display(pd.DataFrame([audit]))
display(descriptive)
display(correlations)

{
  "event_rows": 84,
  "specificity_sentiment_firmyears": 238,
  "matched": 65,
  "missing_specificity_years": [
    {
      "Company": "Chubb",
      "Fiscal Year": 2012
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2013
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2014
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2015
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2016
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2017
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2018
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2019
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2020
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2021
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2022
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2023
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2012
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2013
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2012
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2013
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2015
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2016
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2017
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2020
    }
  ],
  "missing_overall_sentiment_years": [
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2015
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2016
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2017
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2018
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2019
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2020
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2021
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2022
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2023
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2012
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2013
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2012
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2013
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2015
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2016
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2017
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2020
    }
  ],
  "missing_ESG_sentiment_years": [
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2014
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2015
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2016
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2017
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2018
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2019
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2020
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2021
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2022
    },
    {
      "Company": "MetLife, Inc.",
      "Fiscal Year": 2023
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2012
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2013
    },
    {
      "Company": "Prudential Financial, Inc.",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2012
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2013
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2014
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2015
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2016
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2017
    },
    {
      "Company": "The Progressive Corporation",
      "Fiscal Year": 2020
    }
  ],
  "duplicate_event_keys": 0,
  "duplicate_narrative_keys": 0,
  "regression_N": 62,
  "firms": 7
}
(468, 13)

,event_rows,specificity_sentiment_firmyears,matched,missing_specificity_years,missing_overall_sentiment_years,missing_ESG_sentiment_years,duplicate_event_keys,duplicate_narrative_keys,regression_N,firms
0,84,238,65,"[{'Company': 'Chubb', 'Fiscal Year': 2012}, {'...","[{'Company': 'MetLife, Inc.', 'Fiscal Year': 2...","[{'Company': 'MetLife, Inc.', 'Fiscal Year': 2...",0,0,62,7

,count,mean,std,min,25%,50%,75%,max
"CAR[-1,+1]",62.0,-0.004319,0.023535,-0.108074,-0.011677,-0.002793,0.006452,0.041168
"|CAR|[-1,+1]",62.0,0.015576,0.018062,0.000344,0.004232,0.008904,0.021411,0.108074
"CAR[-2,+2]",62.0,-0.003347,0.027896,-0.157925,-0.013817,-0.004850,0.006295,0.053135
"CAR[0,+1]",62.0,-0.002343,0.016166,-0.066438,-0.009557,-0.002415,0.004061,0.048747
"CAR[0,+5]",62.0,-0.009570,0.038251,-0.200539,-0.020306,-0.003931,0.012798,0.065234
"CAR[0,+20]",62.0,-0.004234,0.055292,-0.155833,-0.036657,0.004156,0.030475,0.114812
Specificity_mean,62.0,1.439526,0.229556,1.000000,1.297619,1.439614,1.575549,2.000000
Specificity_all_flagged_mean,62.0,1.201035,0.306566,0.333333,1.081169,1.226496,1.410675,1.875000
Overall_sentiment,62.0,0.473011,0.180340,0.000000,0.334323,0.495098,0.610592,0.770492
ESG_sentiment,62.0,0.359507,0.231813,-0.142857,0.196461,0.376025,0.516304,1.000000

,"CAR[-1,+1]","|CAR|[-1,+1]","CAR[-2,+2]","CAR[0,+1]","CAR[0,+5]","CAR[0,+20]",Specificity_mean,Overall_sentiment,ESG_sentiment
"CAR[-1,+1]",1.000000,-0.542836,0.723857,0.812826,0.465032,-0.011147,-0.056154,-0.140668,-0.051978
"|CAR|[-1,+1]",-0.542836,1.000000,-0.502004,-0.348788,-0.517170,-0.074942,-0.020159,0.156150,0.130615
"CAR[-2,+2]",0.723857,-0.502004,1.000000,0.626206,0.543021,0.181939,-0.125364,-0.160583,-0.006507
"CAR[0,+1]",0.812826,-0.348788,0.626206,1.000000,0.601798,0.271713,-0.136393,-0.080054,-0.004158
"CAR[0,+5]",0.465032,-0.517170,0.543021,0.601798,1.000000,0.572517,-0.100931,0.012274,0.019693
"CAR[0,+20]",-0.011147,-0.074942,0.181939,0.271713,0.572517,1.000000,-0.158441,0.224170,0.213025
Specificity_mean,-0.056154,-0.020159,-0.125364,-0.136393,-0.100931,-0.158441,1.000000,0.109059,0.085607
Overall_sentiment,-0.140668,0.156150,-0.160583,-0.080054,0.012274,0.224170,0.109059,1.000000,0.851685
ESG_sentiment,-0.051978,0.130615,-0.006507,-0.004158,0.019693,0.213025,0.085607,0.851685,1.000000

## Preferred firm and fiscal-year fixed-effects results

HC3 is the main inference. Firm-clustered and wild-cluster results are sensitivity checks because there are only six within-firm clusters.

In [3]:
preferred=results[(results.fixed_effects=='firm_year_FE')&(results.covariance=='HC3')&results.model.isin(['M3_specificity_overall','M3b_specificity_ESG','M4_interaction_overall','M4b_interaction_ESG'])]
display(preferred)
display(pd.read_csv(ROOT/'specificity_car_test/results_sentiment/wild_cluster_bootstrap.csv'))

,outcome,model,fixed_effects,covariance,term,N,firms,coefficient,SE,p_value,CI95_low,CI95_high,R_squared
26,"CAR[-1,+1]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.019915,0.020659,0.340579,-0.061607,0.021777,0.316409
27,"CAR[-1,+1]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,-0.008632,0.046837,0.854671,-0.103153,0.085889,0.316409
38,"CAR[-1,+1]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.024250,0.021540,0.266624,-0.067719,0.019218,0.327632
39,"CAR[-1,+1]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.020492,0.024411,0.405960,-0.028771,0.069756,0.327632
54,"CAR[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,0.024627,0.052810,0.643452,-0.082026,0.131279,0.339088
55,"CAR[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.119716,0.147867,0.422832,-0.178907,0.418340,0.339088
56,"CAR[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,-0.097084,0.117064,0.411723,-0.333500,0.139332,0.339088
72,"CAR[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.012940,0.026902,0.633074,-0.067270,0.041390,0.331277
73,"CAR[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.056413,0.092387,0.544821,-0.130166,0.242992,0.331277
74,"CAR[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,-0.029627,0.074342,0.692315,-0.179764,0.120510,0.331277
104,"|CAR|[-1,+1]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,0.007922,0.015302,0.607350,-0.022958,0.038803,0.392011
105,"|CAR|[-1,+1]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.020161,0.031887,0.530641,-0.044190,0.084513,0.392011
116,"|CAR|[-1,+1]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,0.010749,0.015979,0.504822,-0.021498,0.042997,0.380938
117,"|CAR|[-1,+1]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,-0.000220,0.014728,0.988152,-0.029941,0.029501,0.380938
132,"|CAR|[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.004137,0.038692,0.915364,-0.082278,0.074003,0.394807
133,"|CAR|[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,-0.014590,0.108919,0.894096,-0.234556,0.205376,0.394807
134,"|CAR|[-1,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,0.026286,0.086561,0.762912,-0.148527,0.201099,0.394807
150,"|CAR|[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,0.013571,0.017568,0.444257,-0.021909,0.049052,0.381319
151,"|CAR|[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.008743,0.063582,0.891301,-0.119662,0.137148,0.381319
152,"|CAR|[-1,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,-0.007393,0.050346,0.883981,-0.109068,0.094283,0.381319
182,"CAR[-2,+2]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.027239,0.028178,0.339235,-0.084105,0.029626,0.282081
183,"CAR[-2,+2]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,-0.049442,0.059603,0.411493,-0.169726,0.070841,0.282081
194,"CAR[-2,+2]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.035786,0.029468,0.231374,-0.095255,0.023683,0.257147
195,"CAR[-2,+2]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.011082,0.028842,0.702759,-0.047125,0.069288,0.257147
210,"CAR[-2,+2]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,0.020066,0.070197,0.776430,-0.121700,0.161832,0.299814
211,"CAR[-2,+2]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.086870,0.220203,0.695258,-0.357839,0.531578,0.299814
212,"CAR[-2,+2]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,-0.103108,0.159574,0.521786,-0.425375,0.219159,0.299814
228,"CAR[-2,+2]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.033811,0.033253,0.315227,-0.100967,0.033345,0.257224
229,"CAR[-2,+2]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.017356,0.116688,0.882488,-0.218299,0.253012,0.257224
230,"CAR[-2,+2]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,-0.005175,0.097283,0.957834,-0.201643,0.191292,0.257224
260,"CAR[0,+1]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.016761,0.014441,0.252344,-0.045904,0.012382,0.216652
261,"CAR[0,+1]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.005557,0.036057,0.878256,-0.067209,0.078323,0.216652
272,"CAR[0,+1]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.018864,0.015018,0.216024,-0.049171,0.011443,0.237572
273,"CAR[0,+1]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.018754,0.017166,0.280829,-0.015888,0.053396,0.237572
288,"CAR[0,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,0.032654,0.026846,0.230820,-0.021563,0.086871,0.275571
289,"CAR[0,+1]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.147946,0.082817,0.081427,-0.019306,0.315198,0.275571
290,"CAR[0,+1]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,-0.107705,0.065533,0.107923,-0.240052,0.024642,0.275571
306,"CAR[0,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,0.005468,0.016623,0.743881,-0.028104,0.039040,0.273177
307,"CAR[0,+1]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.096031,0.051017,0.066900,-0.006999,0.199062,0.273177
308,"CAR[0,+1]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,-0.063737,0.042012,0.136906,-0.148581,0.021107,0.273177
338,"CAR[0,+5]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.046144,0.035114,0.195936,-0.117007,0.024719,0.237612
339,"CAR[0,+5]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.042816,0.080960,0.599686,-0.120567,0.206200,0.237612
350,"CAR[0,+5]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.043858,0.038361,0.259393,-0.121274,0.033558,0.232820
351,"CAR[0,+5]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.023796,0.036959,0.523178,-0.050791,0.098382,0.232820
366,"CAR[0,+5]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.008186,0.074598,0.913150,-0.158840,0.142467,0.243712
367,"CAR[0,+5]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.152193,0.211325,0.475497,-0.274587,0.578973,0.243712
368,"CAR[0,+5]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,-0.082734,0.184828,0.656779,-0.456003,0.290534,0.243712
384,"CAR[0,+5]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.024633,0.045225,0.588926,-0.115967,0.066701,0.236720
385,"CAR[0,+5]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.084854,0.138885,0.544593,-0.195629,0.365337,0.236720
386,"CAR[0,+5]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,-0.050360,0.117624,0.670789,-0.287907,0.187187,0.236720
416,"CAR[0,+20]",M3_specificity_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.031324,0.038600,0.421644,-0.109221,0.046573,0.540934
417,"CAR[0,+20]",M3_specificity_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.078392,0.071991,0.282403,-0.066892,0.223677,0.540934
428,"CAR[0,+20]",M3b_specificity_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.027746,0.041586,0.508291,-0.111671,0.056178,0.534890
429,"CAR[0,+20]",M3b_specificity_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.047537,0.050897,0.355649,-0.055177,0.150250,0.534890
444,"CAR[0,+20]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean,61,6,-0.031208,0.080117,0.698902,-0.193007,0.130592,0.540934
445,"CAR[0,+20]",M4_interaction_overall,firm_year_FE,HC3,Overall_sentiment,61,6,0.078727,0.226240,0.729634,-0.378173,0.535628,0.540934
446,"CAR[0,+20]",M4_interaction_overall,firm_year_FE,HC3,Specificity_mean:Overall_sentiment,61,6,-0.000254,0.171792,0.998829,-0.347194,0.346687,0.540934
462,"CAR[0,+20]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean,61,6,-0.038011,0.060338,0.532208,-0.159865,0.083843,0.535445
463,"CAR[0,+20]",M4b_interaction_ESG,firm_year_FE,HC3,ESG_sentiment,61,6,0.014937,0.178646,0.933772,-0.345846,0.375719,0.535445
464,"CAR[0,+20]",M4b_interaction_ESG,firm_year_FE,HC3,Specificity_mean:ESG_sentiment,61,6,0.026888,0.133326,0.841172,-0.242370,0.296146,0.535445

,outcome,model,term,N,firms,p_value
0,"CAR[-1,+1]",M3_specificity_overall,Specificity_mean,61,6,0.71875
1,"CAR[-1,+1]",M3_specificity_overall,Overall_sentiment,61,6,0.78125
2,"CAR[-1,+1]",M3b_specificity_ESG,Specificity_mean,61,6,0.65625
3,"CAR[-1,+1]",M3b_specificity_ESG,ESG_sentiment,61,6,0.03125
4,"CAR[-1,+1]",M4_interaction_overall,Specificity_mean,61,6,0.43750
5,"CAR[-1,+1]",M4_interaction_overall,Overall_sentiment,61,6,0.37500
6,"CAR[-1,+1]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.46875
7,"CAR[-1,+1]",M4b_interaction_ESG,Specificity_mean,61,6,0.62500
8,"CAR[-1,+1]",M4b_interaction_ESG,ESG_sentiment,61,6,0.59375
9,"CAR[-1,+1]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.71875
10,"|CAR|[-1,+1]",M3_specificity_overall,Specificity_mean,61,6,0.75000
11,"|CAR|[-1,+1]",M3_specificity_overall,Overall_sentiment,61,6,0.50000
12,"|CAR|[-1,+1]",M3b_specificity_ESG,Specificity_mean,61,6,0.75000
13,"|CAR|[-1,+1]",M3b_specificity_ESG,ESG_sentiment,61,6,0.90625
14,"|CAR|[-1,+1]",M4_interaction_overall,Specificity_mean,61,6,0.78125
15,"|CAR|[-1,+1]",M4_interaction_overall,Overall_sentiment,61,6,0.81250
16,"|CAR|[-1,+1]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.78125
17,"|CAR|[-1,+1]",M4b_interaction_ESG,Specificity_mean,61,6,0.21875
18,"|CAR|[-1,+1]",M4b_interaction_ESG,ESG_sentiment,61,6,0.87500
19,"|CAR|[-1,+1]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.87500
20,"CAR[-2,+2]",M3_specificity_overall,Specificity_mean,61,6,0.06250
21,"CAR[-2,+2]",M3_specificity_overall,Overall_sentiment,61,6,0.21875
22,"CAR[-2,+2]",M3b_specificity_ESG,Specificity_mean,61,6,0.09375
23,"CAR[-2,+2]",M3b_specificity_ESG,ESG_sentiment,61,6,0.37500
24,"CAR[-2,+2]",M4_interaction_overall,Specificity_mean,61,6,0.53125
25,"CAR[-2,+2]",M4_interaction_overall,Overall_sentiment,61,6,0.37500
26,"CAR[-2,+2]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.25000
27,"CAR[-2,+2]",M4b_interaction_ESG,Specificity_mean,61,6,0.21875
28,"CAR[-2,+2]",M4b_interaction_ESG,ESG_sentiment,61,6,0.81250
29,"CAR[-2,+2]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.90625
30,"CAR[0,+1]",M3_specificity_overall,Specificity_mean,61,6,0.15625
31,"CAR[0,+1]",M3_specificity_overall,Overall_sentiment,61,6,0.81250
32,"CAR[0,+1]",M3b_specificity_ESG,Specificity_mean,61,6,0.15625
33,"CAR[0,+1]",M3b_specificity_ESG,ESG_sentiment,61,6,0.03125
34,"CAR[0,+1]",M4_interaction_overall,Specificity_mean,61,6,0.31250
35,"CAR[0,+1]",M4_interaction_overall,Overall_sentiment,61,6,0.03125
36,"CAR[0,+1]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.15625
37,"CAR[0,+1]",M4b_interaction_ESG,Specificity_mean,61,6,0.68750
38,"CAR[0,+1]",M4b_interaction_ESG,ESG_sentiment,61,6,0.12500
39,"CAR[0,+1]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.18750
40,"CAR[0,+5]",M3_specificity_overall,Specificity_mean,61,6,0.00000
41,"CAR[0,+5]",M3_specificity_overall,Overall_sentiment,61,6,0.43750
42,"CAR[0,+5]",M3b_specificity_ESG,Specificity_mean,61,6,0.31250
43,"CAR[0,+5]",M3b_specificity_ESG,ESG_sentiment,61,6,0.40625
44,"CAR[0,+5]",M4_interaction_overall,Specificity_mean,61,6,0.71875
45,"CAR[0,+5]",M4_interaction_overall,Overall_sentiment,61,6,0.31250
46,"CAR[0,+5]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.75000
47,"CAR[0,+5]",M4b_interaction_ESG,Specificity_mean,61,6,0.43750
48,"CAR[0,+5]",M4b_interaction_ESG,ESG_sentiment,61,6,0.37500
49,"CAR[0,+5]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.46875
50,"CAR[0,+20]",M3_specificity_overall,Specificity_mean,61,6,0.03125
51,"CAR[0,+20]",M3_specificity_overall,Overall_sentiment,61,6,0.06250
52,"CAR[0,+20]",M3b_specificity_ESG,Specificity_mean,61,6,0.09375
53,"CAR[0,+20]",M3b_specificity_ESG,ESG_sentiment,61,6,0.09375
54,"CAR[0,+20]",M4_interaction_overall,Specificity_mean,61,6,0.56250
55,"CAR[0,+20]",M4_interaction_overall,Overall_sentiment,61,6,0.68750
56,"CAR[0,+20]",M4_interaction_overall,Specificity_mean:Overall_sentiment,61,6,0.96875
57,"CAR[0,+20]",M4b_interaction_ESG,Specificity_mean,61,6,0.53125
58,"CAR[0,+20]",M4b_interaction_ESG,ESG_sentiment,61,6,0.93750
59,"CAR[0,+20]",M4b_interaction_ESG,Specificity_mean:ESG_sentiment,61,6,0.68750

## Influence and COVID sensitivities

In [4]:
display(pd.read_csv(ROOT/'specificity_car_test/results_sentiment/influence_diagnostics.csv').sort_values('cooks_distance',ascending=False).head(20))
display(pd.read_csv(ROOT/'specificity_car_test/results_sentiment/influence_COVID_sensitivities.csv'))

,Company,Fiscal Year,outcome,model,studentized_residual,cooks_distance,leverage
129,American International Group (AIG),2019,"|CAR|[-1,+1]",M3_specificity_overall,5.297918,0.404785,0.310632
7,American International Group (AIG),2019,"CAR[-1,+1]",M3_specificity_overall,-5.242959,0.399784,0.310632
190,American International Group (AIG),2019,"|CAR|[-1,+1]",M3b_specificity_ESG,5.416356,0.363589,0.282821
68,American International Group (AIG),2019,"CAR[-1,+1]",M3b_specificity_ESG,-5.286434,0.353340,0.282821
37,The Allstate Corporation,2017,"CAR[-1,+1]",M3_specificity_overall,-1.424115,0.137917,0.569649
79,Chubb,2019,"CAR[-1,+1]",M3b_specificity_ESG,2.634610,0.119244,0.271443
18,Chubb,2019,"CAR[-1,+1]",M3_specificity_overall,2.764525,0.114545,0.248010
213,"Prudential Financial, Inc.",2022,"|CAR|[-1,+1]",M3b_specificity_ESG,2.359417,0.102071,0.278633
228,The Progressive Corporation,2019,"|CAR|[-1,+1]",M3b_specificity_ESG,-1.966004,0.099032,0.342113
152,"Prudential Financial, Inc.",2022,"|CAR|[-1,+1]",M3_specificity_overall,2.316642,0.095850,0.272525
167,The Progressive Corporation,2019,"|CAR|[-1,+1]",M3_specificity_overall,-1.835237,0.091749,0.353486
206,"Prudential Financial, Inc.",2015,"|CAR|[-1,+1]",M3b_specificity_ESG,1.704613,0.071136,0.327166
212,"Prudential Financial, Inc.",2021,"|CAR|[-1,+1]",M3b_specificity_ESG,-1.780651,0.069747,0.305339
159,The Allstate Corporation,2017,"|CAR|[-1,+1]",M3_specificity_overall,0.987798,0.068017,0.569649
229,The Progressive Corporation,2021,"|CAR|[-1,+1]",M3b_specificity_ESG,1.532869,0.064728,0.350741
30,"Prudential Financial, Inc.",2022,"CAR[-1,+1]",M3_specificity_overall,-1.851279,0.063882,0.272525
151,"Prudential Financial, Inc.",2021,"|CAR|[-1,+1]",M3_specificity_overall,-1.631866,0.063144,0.318970
91,"Prudential Financial, Inc.",2022,"CAR[-1,+1]",M3b_specificity_ESG,-1.788264,0.061778,0.278633
39,The Allstate Corporation,2019,"CAR[-1,+1]",M3_specificity_overall,1.774479,0.061762,0.281476
191,American International Group (AIG),2020,"|CAR|[-1,+1]",M3b_specificity_ESG,1.609881,0.059428,0.311381

,outcome,model,scenario,term,N,coefficient,SE,p_value,CI95_low,CI95_high
0,"CAR[-1,+1]",M3_specificity_overall,exclude_most_influential,Specificity_mean,60,-0.007859,0.014203,0.583050,-0.036542,0.020825
1,"CAR[-1,+1]",M3_specificity_overall,exclude_most_influential,Overall_sentiment,60,0.017580,0.028277,0.537570,-0.039526,0.074686
2,"CAR[-1,+1]",M3_specificity_overall,exclude_COVID_period,Specificity_mean,55,-0.008948,0.016126,0.582319,-0.041622,0.023727
3,"CAR[-1,+1]",M3_specificity_overall,exclude_COVID_period,Overall_sentiment,55,-0.009541,0.034775,0.785341,-0.080002,0.060921
4,"CAR[-1,+1]",M3b_specificity_ESG,exclude_most_influential,Specificity_mean,60,-0.009138,0.014804,0.540487,-0.039036,0.020760
5,"CAR[-1,+1]",M3b_specificity_ESG,exclude_most_influential,ESG_sentiment,60,0.021907,0.021050,0.304111,-0.020605,0.064419
6,"CAR[-1,+1]",M3b_specificity_ESG,exclude_COVID_period,Specificity_mean,55,-0.010664,0.015108,0.484671,-0.041275,0.019947
7,"CAR[-1,+1]",M3b_specificity_ESG,exclude_COVID_period,ESG_sentiment,55,0.006851,0.020627,0.741666,-0.034943,0.048644
8,"|CAR|[-1,+1]",M3_specificity_overall,exclude_most_influential,Specificity_mean,60,-0.000899,0.010843,0.934302,-0.022798,0.020999
9,"|CAR|[-1,+1]",M3_specificity_overall,exclude_most_influential,Overall_sentiment,60,0.000982,0.018772,0.958555,-0.036930,0.038893
10,"|CAR|[-1,+1]",M3_specificity_overall,exclude_COVID_period,Specificity_mean,55,-0.000545,0.010826,0.960105,-0.022480,0.021390
11,"|CAR|[-1,+1]",M3_specificity_overall,exclude_COVID_period,Overall_sentiment,55,0.003376,0.019200,0.861384,-0.035527,0.042280
12,"|CAR|[-1,+1]",M3b_specificity_ESG,exclude_most_influential,Specificity_mean,60,-0.000593,0.011081,0.957587,-0.022972,0.021786
13,"|CAR|[-1,+1]",M3b_specificity_ESG,exclude_most_influential,ESG_sentiment,60,-0.001282,0.014263,0.928833,-0.030087,0.027524
14,"|CAR|[-1,+1]",M3b_specificity_ESG,exclude_COVID_period,Specificity_mean,55,0.000130,0.011112,0.990693,-0.022386,0.022647
15,"|CAR|[-1,+1]",M3b_specificity_ESG,exclude_COVID_period,ESG_sentiment,55,-0.002974,0.015036,0.844283,-0.033439,0.027491

## Interpretation

In [5]:
display(Markdown((ROOT/'specificity_car_test/REPORT_SENTIMENT.md').read_text()))

# Specificity, sentiment, and abnormal returns

## Result

The extended analysis finds no statistically detectable association between CEO-letter specificity, overall FinBERT sentiment, ESG-specific sentiment, or their interactions and either signed or absolute three-day CAR under the preferred firm and fiscal-year fixed-effects specification with HC3 inference.

For signed `CAR[-1,+1]`, the joint specificity + overall-sentiment model gives specificity β = −0.0199 (SE 0.0207, p = 0.341) and overall sentiment β = −0.0086 (SE 0.0468, p = 0.855). Replacing overall sentiment with ESG sentiment gives specificity β = −0.0243 (SE 0.0215, p = 0.267) and ESG sentiment β = 0.0205 (SE 0.0244, p = 0.406).

For `|CAR[-1,+1]|`, the corresponding joint coefficients are also nonsignificant: specificity β = 0.0079 (p = 0.607) and overall sentiment β = 0.0202 (p = 0.531); with ESG sentiment, specificity β = 0.0107 (p = 0.505) and ESG sentiment β = −0.0002 (p = 0.988).

Neither interaction is supported. For signed CAR, specificity × overall sentiment has β = −0.0971 (p = 0.412), and specificity × ESG sentiment has β = −0.0296 (p = 0.692). For absolute CAR, their p-values are 0.763 and 0.884. Thus the data do not show that specificity systematically amplifies positive or negative tone.

Alternative windows `[−2,+2]`, `[0,+1]`, `[0,+5]`, and `[0,+20]` do not produce HC3-significant coefficients in the preferred joint or interaction models. A few six-cluster wild-bootstrap p-values are small while HC3 results are not, including a zero p-value for one `[0,+5]` coefficient. With only six within-firm clusters and 64 possible Rademacher sign patterns, these coarse and conflicting bootstrap results are treated as unstable sensitivity signals, not confirmatory evidence.

## Merge and variables

The event panel has 84 unique insurer-years. Sixty-five match the sentence-level narrative outputs; 62 contain primary specificity, overall sentiment, and ESG sentiment. The pooled regressions use N=62 across seven firms. Fixed-effects regressions remove MetLife's single eligible observation and use N=61 across six firms.

Primary `Specificity_mean` is the validated paper measure: mean tier among Corporate ESG sentences with tier ≥1. Tier 0 represents a false positive, so it is not relabeled “generic” or included in the primary mean. `Specificity_all_flagged_mean` records the proposed 0–3 mean over every classified ESG-flagged sentence as a robustness variable. The re-aggregated primary measure agrees with the prior regression panel to numerical precision.

`Overall_sentiment` equals the share of all CEO-letter sentences labeled positive minus the share labeled negative. `ESG_sentiment` uses the same formula among sentences with `any_esg_flag == 1`. Both use the existing FinBERT discrete labels.

The longer `[0,+5]` and `[0,+20]` CARs use the saved event-study alpha and beta and the same archived adjusted stock and URTH prices. They contain 6 and 21 observed sessions, including the adjusted event day.

## Influence and data quality

AIG FY2019 remains the most influential primary-window observation. Excluding the most influential observation or all March–April 2020 publication events materially attenuates several estimates but does not create HC3-significant primary associations.

The specificity source contains 62 exact duplicate rows and the FinBERT source contains 125 exact duplicate rows. These duplicates were already present in the inputs underlying the validated paper measure. They were retained for comparability and explicitly reported rather than silently deleted. A future data-cleaning revision should investigate their origin and rerun the analysis after a documented deduplication rule.

The conclusions are associational. Annual-report publication events may bundle other value-relevant information, and publication dates have not been independently authenticated against original filings and timestamps.

In [6]:
assert audit['event_rows']==84 and audit['regression_N']==62
assert len(results)==468
assert results[['coefficient','SE','p_value','CI95_low','CI95_high']].notna().all().all()
print('Validated extended analysis outputs.')

Validated extended analysis outputs.